var filmliste = [
{"Title":"Killer's Kiss","Year":"1955","Rated":"NOT RATED","Released":"01 Oct 1955","Runtime":"67 min","Genre":"Crime, Drama, Film-Noir","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (story)","Actors":"Frank Silvera, Jamie Smith, Irene Kane, Jerry Jarrett","Plot":"Prize-fighter Davy Gordon intervenes when private dancer Gloria Price is being attacked by her employer and lover Vincent Raphello. This brings the two together and they get involved with each other, which displeases Raphello. He sends men out to kill Davy, but they instead kill his friend. Gloria is soon kidnapped by Raphello and his men, and it is up to Davy to save her.","Language":"English","Country":"USA","Awards":"1 win.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BM2FiNjRlMWQtNDk0Ny00OTA0LWI0ZjEtNTM4NmZlZTllZDFlXkEyXkFqcGdeQXVyNjMxMzM3NDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.7/10"},{"Source":"Rotten Tomatoes","Value":"84%"}],"Metascore":"N/A","imdbRating":"6.7","imdbVotes":"17,078","imdbID":"tt0048254","Type":"movie","DVD":"15 May 2001","BoxOffice":"N/A","Production":"United Artists","Website":"N/A","Response":"True"},
{"Title":"The Killing","Year":"1956","Rated":"NOT RATED","Released":"06 Jun 1956","Runtime":"85 min","Genre":"Crime, Drama, Film-Noir","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (screenplay), Jim Thompson (dialogue), Lionel White (novel)","Actors":"Sterling Hayden, Coleen Gray, Vince Edwards, Jay C. Flippen","Plot":"After getting out of prison, Johnny Clay masterminds a complex race-track heist, but his scheme is complicated by the intervention of the wife of a teller (George Peatty) in on the scheme, the boyfriend of the wife, airport regulations, and a small dog.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMDE5ZjAwY2YtOWM5Yi00ZWNlLWE5ODQtYjA4NzA1NGFkZDU5XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"97%"}],"Metascore":"N/A","imdbRating":"8.0","imdbVotes":"67,149","imdbID":"tt0049406","Type":"movie","DVD":"15 Aug 2001","BoxOffice":"N/A","Production":"United Artists","Website":"http://www.amctv.com/shows/the-killing","Response":"True"},
{"Title":"Paths of Glory","Year":"1957","Rated":"NOT RATED","Released":"01 Nov 1957","Runtime":"88 min","Genre":"Drama, War","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (screenplay), Calder Willingham (screenplay), Jim Thompson (screenplay), Humphrey Cobb (based on the novel \"Paths of Glory\" by)","Actors":"Kirk Douglas, Ralph Meeker, Adolphe Menjou, George Macready","Plot":"The futility and irony of the war in the trenches in WWI is shown as a unit commander in the French army must deal with the mutiny of his men and a glory-seeking general after part of his force falls back under fire in an impossible attack.","Language":"English, German, Latin","Country":"USA","Awards":"Nominated for 1 BAFTA Film Award. Another 4 wins & 2 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BOTI5Nzc0OTMtYzBkMS00NjkxLThmM2UtNjM2ODgxN2M5NjNkXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"94%"}],"Metascore":"N/A","imdbRating":"8.5","imdbVotes":"135,138","imdbID":"tt0050825","Type":"movie","DVD":"15 May 2001","BoxOffice":"N/A","Production":"United Artists","Website":"N/A","Response":"True"},
{"Title":"Spartacus","Year":"1960","Rated":"PG-13","Released":"17 Nov 1960","Runtime":"197 min","Genre":"Adventure, Biography, Drama","Director":"Stanley Kubrick","Writer":"Dalton Trumbo (screenplay), Howard Fast (based on the novel by)","Actors":"Kirk Douglas, Laurence Olivier, Jean Simmons, Charles Laughton","Plot":"In 73 BCE, a Thracian slave leads a revolt at a gladiatorial school run by Lentulus Batiatus. The uprising soon spreads across the Italian Peninsula involving thousand of slaves. The plan is to acquire sufficient funds to acquire ships from Silesian pirates who could then transport them to other lands from Brandisium in the south. The Roman Senator Gracchus schemes to have Marcus Publius Glabrus, Commander of the garrison of Rome, lead an army against the slaves who are living on Vesuvius. When Glabrus is defeated his mentor, Senator and General Marcus Licinius Crassus is greatly embarrassed and leads his own army against the slaves. Spartacus and the thousands of freed slaves successfully make their way to Brandisium only to find that the Silesians have abandoned them. They then turn north and must face the might of Rome.","Language":"English","Country":"USA","Awards":"Won 4 Oscars. Another 6 wins & 11 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjc4MTUxN2UtMmU1NC00MjQyLTk3YTYtZTQ0YzEzZDc0Njc0XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"87/100"}],"Metascore":"87","imdbRating":"7.9","imdbVotes":"104,734","imdbID":"tt0054331","Type":"movie","DVD":"24 Apr 2001","BoxOffice":"N/A","Production":"Universal Pictures","Website":"N/A","Response":"True"},
{"Title":"Lolita","Year":"1962","Rated":"APPROVED","Released":"01 Sep 1962","Runtime":"153 min","Genre":"Crime, Drama, Romance","Director":"Stanley Kubrick","Writer":"Vladimir Nabokov (screenplay), Vladimir Nabokov (novel)","Actors":"James Mason, Shelley Winters, Sue Lyon, Gary Cockrell","Plot":"Humbert Humbert forces a confrontation with a man, whose name he has just recently learned, in this man's home. The events that led to this standoff began four years earlier. Middle aged Humbert, a European, arrives in the United States where he has secured at job at Beardsley College in Beardsley, Ohio as a Professor of French Literature. Before he begins his post in the fall, he decides to spend the summer in the resort town of Ramsdale, New Hampshire. He is given the name of Charlotte Haze as someone who is renting a room in her home for the summer. He finds that Charlotte, widowed now for seven years, is a woman who puts on airs. Among the demonstration of those airs is throwing around the name of Clare Quilty, a television and stage script writer, who came to speak at her women's club meeting and who she implies is now a friend. Those airs also mask being lonely, especially as she is a sexually aggressive and liberated woman. Humbert considers Charlotte a proverbial \"joke\" but decides to rent the room upon meeting Charlotte's provocative daughter, Dolores Haze - more frequently referred to as Lolita - who he first spots in a bikini tanning in the back yard. He is immediately infatuated with Lolita, with who he becomes obsessed in a sexual manner despite her age, she being just into her teens. He will also learn that Charlotte has the exact same feelings for him. While Charlotte does whatever she can to be alone with Humbert, Humbert does the same with Lolita. As the summer progresses, Humbert, based on the circumstances, decides to enter into a relationship with Charlotte just to be near Lolita. In that new arrangement, Humbert has to figure out how to achieve his goal of being with Lolita with Charlotte out of the way. As things begin to go Humbert's way, he is unaware that Charlotte is not the only thing standing in his way between him and Lolita, that other thing being Lolita's possible interest in other boys, and other members of the male sex, young or old, who may have their own designs on Lolita.","Language":"English, French, Spanish, German","Country":"UK, USA","Awards":"Nominated for 1 Oscar. Another 2 wins & 8 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZTlmODM0ZTgtY2NkZS00Y2ZmLTkxMzktMTE4ZDg2NzNmNDkwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"95%"}],"Metascore":"N/A","imdbRating":"7.6","imdbVotes":"74,308","imdbID":"tt0056193","Type":"movie","DVD":"29 Jun 1999","BoxOffice":"N/A","Production":"MGM","Website":"N/A","Response":"True"},
{"Title":"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","Year":"1964","Rated":"PG","Released":"29 Jan 1964","Runtime":"95 min","Genre":"Comedy","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (screenplay), Terry Southern (screenplay), Peter George (screenplay), Peter George (based on the book: \"Red Alert\" by)","Actors":"Peter Sellers, George C. Scott, Sterling Hayden, Keenan Wynn","Plot":"Paranoid Brigadier General Jack D. Ripper of Burpelson Air Force Base, believing that fluoridation of the American water supply is a Soviet plot to poison the U.S. populace, is able to deploy through a back door mechanism a nuclear attack on the Soviet Union without the knowledge of his superiors, including the Chair of the Joint Chiefs of Staff, General Buck Turgidson, and President Merkin Muffley. Only Ripper knows the code to recall the B-52 bombers and he has shut down communication in and out of Burpelson as a measure to protect this attack. Ripper's executive officer, RAF Group Captain Lionel Mandrake (on exchange from Britain), who is being held at Burpelson by Ripper, believes he knows the recall codes if he can only get a message to the outside world. Meanwhile at the Pentagon War Room, key persons including Muffley, Turgidson and nuclear scientist and adviser, a former Nazi named Dr. Strangelove, are discussing measures to stop the attack or mitigate its blow-up into an all out nuclear war with the Soviets. Against Turgidson's wishes, Muffley brings Soviet Ambassador Alexi de Sadesky into the War Room, and get his boss, Soviet Premier Dimitri Kisov, on the hot line to inform him of what's going on. The Americans in the War Room are dismayed to learn that the Soviets have an as yet unannounced Doomsday Device to detonate if any of their key targets are hit. As Ripper, Mandrake and those in the War Room try and work the situation to their end goal, Major T.J. \"King\" Kong, one of the B-52 bomber pilots, is working on his own agenda of deploying his bomb where ever he can on enemy soil if he can't make it to his intended target.","Language":"English, Russian","Country":"USA, UK","Awards":"Nominated for 4 Oscars. Another 13 wins & 7 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNTkxYjUxNDYtZGY0My00NTc2LThiZmYtNmNmNmU0NGVkZWYwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"99%"},{"Source":"Metacritic","Value":"96/100"}],"Metascore":"96","imdbRating":"8.5","imdbVotes":"373,945","imdbID":"tt0057012","Type":"movie","DVD":"02 Nov 2004","BoxOffice":"N/A","Production":"Sony Pictures","Website":"N/A","Response":"True"},
{"Title":"2001: A Space Odyssey","Year":"1968","Rated":"G","Released":"12 May 1968","Runtime":"149 min","Genre":"Adventure, Sci-Fi","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (screenplay), Arthur C. Clarke (screenplay)","Actors":"Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter","Plot":"\"2001\" is a story of evolution. Sometime in the distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere throughout the universe as well). Evolution then enabled humankind to reach the moon's surface, where yet another monolith is found, one that signals the monolith placers that humankind has evolved that far. Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers. The winner will achieve the next step in evolution, whatever that may be.","Language":"English, Russian","Country":"UK, USA","Awards":"Won 1 Oscar. Another 13 wins & 10 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTZkZTBhYmUtMTIzNy00YTViLTg1OWItNGUwMmVlN2FjZTVkXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"86/100"}],"Metascore":"86","imdbRating":"8.3","imdbVotes":"476,338","imdbID":"tt0062622","Type":"movie","DVD":"25 Aug 1998","BoxOffice":"$135,620","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
{"Title":"Fear and Desire","Year":"1953","Rated":"NOT RATED","Released":"01 Apr 1953","Runtime":"62 min","Genre":"Drama, Thriller, War","Director":"Stanley Kubrick","Writer":"Howard Sackler","Actors":"Frank Silvera, Kenneth Harp, Paul Mazursky, Stephen Coit","Plot":"A ficticious war in an unidentified country provides the setting for this drama. Four soldiers survive the crash-landing of their plane to find themselves in a forest six miles behind enemy lines. The group, led by Lt. Corby, has a plan: They'll make their way to a nearby river, build a raft, and then, under cover of night, float back to friendly territory. Their plans for getting back safely are sidetracked by a young woman who stumbles across them as they hide in the woods, and by the nearby presence of an enemy general who one member of the group is determined to kill.","Language":"English","Country":"USA","Awards":"1 nomination.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDk1ZDAyZGQtNDBmOC00NTBmLTlhZDAtZWVkNTE5ZDY0NWJjXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.6/10"},{"Source":"Rotten Tomatoes","Value":"83%"}],"Metascore":"N/A","imdbRating":"5.6","imdbVotes":"6,199","imdbID":"tt0045758","Type":"movie","DVD":"01 Dec 2013","BoxOffice":"N/A","Production":"Joseph Burstyn Incorporated","Website":"N/A","Response":"True"},
{"Title":"A Clockwork Orange","Year":"1971","Rated":"R","Released":"02 Feb 1972","Runtime":"136 min","Genre":"Crime, Drama, Sci-Fi","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (screenplay), Anthony Burgess (novel)","Actors":"Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke","Plot":"Protagonist Alex DeLarge is an \"ultraviolent\" youth in futuristic Britain. As with all luck, his eventually runs out and he's arrested and convicted of murder and rape. While in prison, Alex learns of an experimental program in which convicts are programmed to detest violence. If he goes through the program, his sentence will be reduced and he will be back on the streets sooner than expected. But Alex's ordeals are far from over once he hits the mean streets of Britain that he had a hand in creating.","Language":"English","Country":"UK, USA","Awards":"Nominated for 4 Oscars. Another 9 wins & 19 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"90%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"8.3","imdbVotes":"617,233","imdbID":"tt0066921","Type":"movie","DVD":"29 Jun 1999","BoxOffice":"N/A","Production":"Warner Bros.","Website":"N/A","Response":"True"},
{"Title":"Barry Lyndon","Year":"1975","Rated":"PG","Released":"18 Dec 1975","Runtime":"184 min","Genre":"Adventure, Drama, History","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (written for the screen by), William Makepeace Thackeray (novel)","Actors":"Ryan O'Neal, Marisa Berenson, Patrick Magee, Hardy Krüger","Plot":"In the Eighteenth Century, in a small village in Ireland, Redmond Barry is a young farm boy in love with his cousin Nora Brady. When Nora gets engaged to the British Captain John Quin, Barry challenges him to a duel of pistols. He wins and escapes to Dublin but is robbed on the road. Without an alternative, Barry joins the British Army to fight in the Seven Years War. He deserts and is forced to join the Prussian Army where he saves the life of his captain and becomes his protégé and spy of the Irish gambler Chevalier de Balibari. He helps Chevalier and becomes his associate until he decides to marry the wealthy Lady Lyndon. They move to England and Barry, in his obsession of nobility, dissipates her fortune and makes a dangerous and revengeful enemy.","Language":"English, German, French","Country":"UK, USA, Ireland","Awards":"Won 4 Oscars. Another 13 wins & 14 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMmQyMTNjYWUtYzAxMC00NjRkLThlODUtNWViMTAzM2ZmNzJkXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"97%"}],"Metascore":"N/A","imdbRating":"8.1","imdbVotes":"113,180","imdbID":"tt0072684","Type":"movie","DVD":"29 Jun 1999","BoxOffice":"N/A","Production":"Warner Bros.","Website":"N/A","Response":"True"},
{"Title":"Full Metal Jacket","Year":"1987","Rated":"R","Released":"10 Jul 1987","Runtime":"116 min","Genre":"Drama, War","Director":"Stanley Kubrick","Writer":"Gustav Hasford (novel), Stanley Kubrick (screenplay), Michael Herr (screenplay), Gustav Hasford (screenplay)","Actors":"Matthew Modine, Adam Baldwin, Vincent D'Onofrio, R. Lee Ermey","Plot":"A two-segment look at the effect of the military mindset and war itself on Vietnam era Marines. The first half follows a group of recruits in boot camp under the command of the punishing Gunnery Sergeant Hartman. The second half shows one of those recruits, Joker, covering the war as a correspondent for Stars and Stripes, focusing on the Tet offensive.","Language":"English, Vietnamese","Country":"UK, USA","Awards":"Nominated for 1 Oscar. Another 7 wins & 11 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzc2ZThkOGItZGY5YS00MDYwLTkyOTAtNDRmZWIwMGRhYTc0L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"95%"},{"Source":"Metacritic","Value":"76/100"}],"Metascore":"76","imdbRating":"8.3","imdbVotes":"538,062","imdbID":"tt0093058","Type":"movie","DVD":"29 Jun 1999","BoxOffice":"N/A","Production":"Warner Bros.","Website":"N/A","Response":"True"},
{"Title":"Eyes Wide Shut","Year":"1999","Rated":"R","Released":"16 Jul 1999","Runtime":"159 min","Genre":"Drama, Mystery, Thriller","Director":"Stanley Kubrick","Writer":"Stanley Kubrick (screenplay), Frederic Raphael (screenplay), Arthur Schnitzler (inspired by the novel by)","Actors":"Tom Cruise, Nicole Kidman, Sydney Pollack, Marie Richardson","Plot":"After his wife, Alice, tells him about her sexual fantasies, William Harford sets out for a night of sexual adventure. After several less than successful encounters, he meets an old friend, Nick Nightingale - now a musician - who tells him of strange sex parties when he is required to play the piano blindfolded. All the men at the party are costumed and wear masks while the women are all young and beautiful. Harford manages to find an appropriate costume and heads out to the party. Once there, however, he is warned by someone who recognizes him, despite the mask, that he is in great danger. He manages to extricate himself but the threats prove to be quite real and sinister.","Language":"English","Country":"UK, USA","Awards":"Nominated for 1 Golden Globe. Another 7 wins & 26 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5NTUwNjI1N15BMl5BanBnXkFtZTYwOTE1ODc5._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"74%"},{"Source":"Metacritic","Value":"68/100"}],"Metascore":"68","imdbRating":"7.3","imdbVotes":"246,581","imdbID":"tt0120663","Type":"movie","DVD":"07 Mar 2000","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"http://eyeswideshut.warnerbros.com","Response":"True"},
{"Title":"Harry Potter and the Sorcerer's Stone","Year":"2001","Rated":"PG","Released":"16 Nov 2001","Runtime":"152 min","Genre":"Adventure, Family, Fantasy","Director":"Chris Columbus","Writer":"J.K. Rowling (novel), Steve Kloves (screenplay)","Actors":"Richard Harris, Maggie Smith, Robbie Coltrane, Saunders Triplets","Plot":"This is the tale of Harry Potter, an ordinary 11-year-old boy serving as a sort of slave for his aunt and uncle who learns that he is actually a wizard and has been invited to attend the Hogwarts School for Witchcraft and Wizardry. Harry is snatched away from his mundane existence by Hagrid, the grounds keeper for Hogwarts, and quickly thrown into a world completely foreign to both him and the viewer. Famous for an incident that happened at his birth, Harry makes friends easily at his new school. He soon finds, however, that the wizarding world is far more dangerous for him than he would have imagined, and he quickly learns that not all wizards are ones to be trusted.","Language":"English","Country":"UK, USA","Awards":"Nominated for 3 Oscars. Another 17 wins & 62 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},{"Source":"Rotten Tomatoes","Value":"80%"},{"Source":"Metacritic","Value":"64/100"}],"Metascore":"64","imdbRating":"7.5","imdbVotes":"500,024","imdbID":"tt0241527","Type":"movie","DVD":"28 May 2002","BoxOffice":"$317,557,891","Production":"Warner Bros. Pictures","Website":"http://movies.warnerbros.com/awards/harry.html","Response":"True"},
{"Title":"Harry Potter and the Deathly Hallows: Part 2","Year":"2011","Rated":"PG-13","Released":"15 Jul 2011","Runtime":"130 min","Genre":"Adventure, Drama, Fantasy","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe","Plot":"Harry, Ron, and Hermione continue their quest of finding and destroying the Dark Lord's three remaining Horcruxes, the magical items responsible for his immortality. But as the mystical Deathly Hallows are uncovered, and Voldemort finds out about their mission, the biggest battle begins and life as they know it will never be the same again.","Language":"English","Country":"USA, UK","Awards":"Nominated for 3 Oscars. Another 45 wins & 92 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjIyZGU4YzUtNDkzYi00ZDRhLTljYzctYTMxMDQ4M2E0Y2YxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"87/100"}],"Metascore":"87","imdbRating":"8.1","imdbVotes":"611,697","imdbID":"tt1201607","Type":"movie","DVD":"11 Nov 2011","BoxOffice":"$381,000,185","Production":"Warner Bros. Pictures","Website":"http://www.HarryPotter.com/","Response":"True"},
{"Title":"Harry Potter and the Chamber of Secrets","Year":"2002","Rated":"PG","Released":"15 Nov 2002","Runtime":"161 min","Genre":"Adventure, Family, Fantasy","Director":"Chris Columbus","Writer":"J.K. Rowling (novel), Steve Kloves (screenplay)","Actors":"Daniel Radcliffe, Rupert Grint, Emma Watson, Richard Griffiths","Plot":"Forced to spend his summer holidays with his muggle relations, Harry Potter gets a real shock when he gets a surprise visitor: Dobby the house-elf, who warns Harry Potter against returning to Hogwarts, for terrible things are going to happen. Harry decides to ignore Dobby's warning and continues with his pre-arranged schedule. But at Hogwarts, strange and terrible things are indeed happening: Harry is suddenly hearing mysterious voices from inside the walls, muggle-born students are being attacked, and a message scrawled on the wall in blood puts everyone on his/her guard - \"The Chamber Of Secrets Has Been Opened. Enemies Of The Heir, Beware\" .","Language":"English","Country":"UK, USA, Germany","Awards":"Nominated for 3 BAFTA Film Awards. Another 11 wins & 42 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTcxODgwMDkxNV5BMl5BanBnXkFtZTYwMDk2MDg3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Rotten Tomatoes","Value":"82%"},{"Source":"Metacritic","Value":"63/100"}],"Metascore":"63","imdbRating":"7.4","imdbVotes":"434,310","imdbID":"tt0295297","Type":"movie","DVD":"11 Apr 2003","BoxOffice":"$261,835,892","Production":"Warner Bros. Pictures","Website":"http://harrypotter.warnerbros.com/","Response":"True"},
{"Title":"Harry Potter and the Prisoner of Azkaban","Year":"2004","Rated":"PG","Released":"04 Jun 2004","Runtime":"142 min","Genre":"Adventure, Family, Fantasy","Director":"Alfonso Cuarón","Writer":"J.K. Rowling (novel), Steve Kloves (screenplay)","Actors":"Daniel Radcliffe, Richard Griffiths, Pam Ferris, Fiona Shaw","Plot":"Harry Potter is having a tough time with his relatives (yet again). He runs away after using magic to inflate Uncle Vernon's sister Marge who was being offensive towards Harry's parents. Initially scared for using magic outside the school, he is pleasantly surprised that he won't be penalized after all. However, he soon learns that a dangerous criminal and Voldemort's trusted aide Sirius Black has escaped from the Azkaban prison and wants to kill Harry to avenge the Dark Lord. To worsen the conditions for Harry, vile creatures called Dementors are appointed to guard the school gates and inexplicably happen to have the most horrible effect on him. Little does Harry know that by the end of this year, many holes in his past (whatever he knows of it) will be filled up and he will have a clearer vision of what the future has in store...","Language":"English","Country":"UK, USA","Awards":"Nominated for 2 Oscars. Another 14 wins & 45 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4NTIwODg0N15BMl5BanBnXkFtZTcwOTc0MjEzMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"91%"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"7.8","imdbVotes":"429,333","imdbID":"tt0304141","Type":"movie","DVD":"22 Nov 2004","BoxOffice":"$249,358,727","Production":"Warner Bros. Pictures","Website":"http://azkaban.warnerbros.com/","Response":"True"},
{"Title":"The Shining","Year":"1980","Rated":"R","Released":"13 Jun 1980","Runtime":"146 min","Genre":"Drama, Horror","Director":"Stanley Kubrick","Writer":"Stephen King (novel), Stanley Kubrick (screenplay), Diane Johnson (screenplay)","Actors":"Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers","Plot":"Signing a contract, Jack Torrance, a normal writer and former teacher agrees to take care of a hotel which has a long, violent past that puts everyone in the hotel in a nervous situation. While Jack slowly gets more violent and angry of his life, his son, Danny, tries to use a special talent, the \"Shining\", to inform the people outside about whatever that is going on in the hotel.","Language":"English","Country":"UK, USA","Awards":"3 wins & 7 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"61/100"}],"Metascore":"61","imdbRating":"8.4","imdbVotes":"679,810","imdbID":"tt0081505","Type":"movie","DVD":"29 Jun 1999","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
{"Title":"Harry Potter and the Goblet of Fire","Year":"2005","Rated":"PG-13","Released":"18 Nov 2005","Runtime":"157 min","Genre":"Adventure, Family, Fantasy","Director":"Mike Newell","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Eric Sykes, Timothy Spall, David Tennant, Daniel Radcliffe","Plot":"Harry's fourth year at Hogwarts is about to start and he is enjoying the summer vacation with his friends. They get the tickets to The Quidditch World Cup Final but after the match is over, people dressed like Lord Voldemort's 'Death Eaters' set a fire to all the visitors' tents, coupled with the appearance of Voldemort's symbol, the 'Dark Mark' in the sky, which causes a frenzy across the magical community. That same year, Hogwarts is hosting 'The Triwizard Tournament', a magical tournament between three well-known schools of magic : Hogwarts, Beauxbatons and Durmstrang. The contestants have to be above the age of 17, and are chosen by a magical object called Goblet of Fire. On the night of selection, however, the Goblet spews out four names instead of the usual three, with Harry unwittingly being selected as the Fourth Champion. Since the magic cannot be reversed, Harry is forced to go with it and brave three exceedingly difficult tasks.","Language":"English, French","Country":"UK, USA","Awards":"Nominated for 1 Oscar. Another 13 wins & 42 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"88%"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"7.7","imdbVotes":"430,197","imdbID":"tt0330373","Type":"movie","DVD":"07 Mar 2006","BoxOffice":"$289,994,397","Production":"Warner Bros. Pictures","Website":"http://harrypotter.warnerbros.com/gobletoffire/","Response":"True"},
{"Title":"Harry Potter and the Order of the Phoenix","Year":"2007","Rated":"PG-13","Released":"11 Jul 2007","Runtime":"138 min","Genre":"Adventure, Family, Fantasy","Director":"David Yates","Writer":"Michael Goldenberg (screenplay), J.K. Rowling (novel)","Actors":"Daniel Radcliffe, Harry Melling, Jason Boyd, Richard Macklin","Plot":"After a lonely summer on Privet Drive, Harry returns to a Hogwarts full of ill-fortune. Few of students and parents believe him or Dumbledore that Voldemort is really back. The ministry had decided to step in by appointing a new Defence Against the Dark Arts teacher that proves to be the nastiest person Harry has ever encountered. Harry also can't help stealing glances with the beautiful Cho Chang. To top it off are dreams that Harry can't explain, and a mystery behind something Voldemort is searching for. With these many things Harry begins one of his toughest years at Hogwarts School of Witchcraft and Wizardry.","Language":"English","Country":"UK, USA","Awards":"Nominated for 2 BAFTA Film Awards. Another 14 wins & 40 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTM0NTczMTUzOV5BMl5BanBnXkFtZTYwMzIxNTg3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},{"Source":"Rotten Tomatoes","Value":"78%"},{"Source":"Metacritic","Value":"71/100"}],"Metascore":"71","imdbRating":"7.5","imdbVotes":"396,337","imdbID":"tt0373889","Type":"movie","DVD":"11 Nov 2007","BoxOffice":"$291,980,108","Production":"Warner Bros. Pictures","Website":"http://www.harrypotterorderofthephoenix.com/","Response":"True"},
{"Title":"Harry Potter and the Half-Blood Prince","Year":"2009","Rated":"PG","Released":"15 Jul 2009","Runtime":"153 min","Genre":"Adventure, Family, Fantasy","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Daniel Radcliffe, Michael Gambon, Dave Legeno, Elarica Johnson","Plot":"In the sixth year at Hogwarts School of Witchcraft, and in both wizard and muggle worlds Lord Voldemort and his henchmen are increasingly active. With vacancies to fill at Hogwarts, Professor Dumbledore persuades Horace Slughorn, back from retirement to become the potions teacher, while Professor Snape receives long awaited news. Harry Potter, together with Dumbledore, must face treacherous tasks to defeat his evil nemesis.","Language":"English","Country":"UK, USA","Awards":"Nominated for 1 Oscar. Another 8 wins & 35 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},{"Source":"Rotten Tomatoes","Value":"84%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"7.5","imdbVotes":"363,371","imdbID":"tt0417741","Type":"movie","DVD":"08 Dec 2009","BoxOffice":"$301,920,409","Production":"Warner Bros. Pictures","Website":"http://www.harrypotter.com/","Response":"True"},
{"Title":"Harry Potter and the Deathly Hallows: Part 1","Year":"2010","Rated":"PG-13","Released":"19 Nov 2010","Runtime":"146 min","Genre":"Adventure, Family, Fantasy","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Bill Nighy, Emma Watson, Richard Griffiths, Harry Melling","Plot":"Voldemort's power is growing stronger. He now has control over the Ministry of Magic and Hogwarts. Harry, Ron, and Hermione decide to finish Dumbledore's work and find the rest of the Horcruxes to defeat the Dark Lord. But little hope remains for the Trio, and the rest of the Wizarding World, so everything they do must go as planned.","Language":"English","Country":"UK, USA","Awards":"Nominated for 2 Oscars. Another 16 wins & 53 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"78%"},{"Source":"Metacritic","Value":"65/100"}],"Metascore":"65","imdbRating":"7.7","imdbVotes":"369,752","imdbID":"tt0926084","Type":"movie","DVD":"15 Apr 2011","BoxOffice":"$294,980,434","Production":"Warner Bros. Pictures","Website":"http://www.HarryPotter.com/","Response":"True"},
{"Title":"Alien: Covenant","Year":"2017","Rated":"R","Released":"19 May 2017","Runtime":"122 min","Genre":"Horror, Sci-Fi, Thriller","Director":"Ridley Scott","Writer":"Dan O'Bannon (based on characters created by), Ronald Shusett (based on characters created by), Jack Paglen (story by), Michael Green (story by), John Logan (screenplay by), Dante Harper (screenplay by)","Actors":"Michael Fassbender, Katherine Waterston, Billy Crudup, Danny McBride","Plot":"The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise, but is actually a dark, dangerous world. When they uncover a threat beyond their imagination, they must attempt a harrowing escape","Language":"English","Country":"USA, UK","Awards":"1 win & 6 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzI5MzM3MzkxNF5BMl5BanBnXkFtZTgwOTkyMjI4MTI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.5/10"},{"Source":"Rotten Tomatoes","Value":"69%"},{"Source":"Metacritic","Value":"65/100"}],"Metascore":"65","imdbRating":"6.5","imdbVotes":"166,955","imdbID":"tt2316204","Type":"movie","DVD":"15 Aug 2017","BoxOffice":"$74,255,908","Production":"20th Century Fox","Website":"http://www.foxmovies.com/movies/alien-covenant","Response":"True"},
{"Title":"The Martian","Year":"2015","Rated":"PG-13","Released":"02 Oct 2015","Runtime":"144 min","Genre":"Adventure, Drama, Sci-Fi","Director":"Ridley Scott","Writer":"Drew Goddard (screenplay by), Andy Weir (based on the novel by)","Actors":"Matt Damon, Jessica Chastain, Kristen Wiig, Jeff Daniels","Plot":"During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive. Millions of miles away, NASA and a team of international scientists work tirelessly to bring \"the Martian\" home, while his crewmates concurrently plot a daring, if not impossible, rescue mission. As these stories of incredible bravery unfold, the world comes together to root for Watney's safe return.","Language":"English, Mandarin","Country":"UK, USA","Awards":"Nominated for 7 Oscars. Another 37 wins & 185 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"91%"},{"Source":"Metacritic","Value":"80/100"}],"Metascore":"80","imdbRating":"8.0","imdbVotes":"583,461","imdbID":"tt3659388","Type":"movie","DVD":"12 Jan 2016","BoxOffice":"$202,313,768","Production":"20th Century Fox","Website":"http://TheMartianMovie.com","Response":"True"},
{"Title":"Exodus: Gods and Kings","Year":"2014","Rated":"PG-13","Released":"12 Dec 2014","Runtime":"150 min","Genre":"Action, Adventure, Drama","Director":"Ridley Scott","Writer":"Adam Cooper, Bill Collage, Jeffrey Caine, Steven Zaillian","Actors":"Christian Bale, Joel Edgerton, John Turturro, Aaron Paul","Plot":"Epic adventure Exodus: Gods and Kings is the story of one man's daring courage to take on the might of an empire. Using state of the art visual effects and 3D immersion, Scott brings new life to the story of the defiant leader Moses as he rises up against the Egyptian Pharaoh Ramses, setting 600,000 slaves on a monumental journey of escape from Egypt and its terrifying cycle of deadly plagues.","Language":"English","Country":"UK, Spain, USA","Awards":"5 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjI3MDY0NjkxNl5BMl5BanBnXkFtZTgwNTM3NTA0MzE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.0/10"},{"Source":"Rotten Tomatoes","Value":"27%"},{"Source":"Metacritic","Value":"52/100"}],"Metascore":"52","imdbRating":"6.0","imdbVotes":"140,692","imdbID":"tt1528100","Type":"movie","DVD":"17 Mar 2015","BoxOffice":"N/A","Production":"20th Century Fox","Website":"http://www.exodusgodsandkings.com/","Response":"True"},
{"Title":"Prometheus","Year":"2012","Rated":"R","Released":"08 Jun 2012","Runtime":"124 min","Genre":"Adventure, Mystery, Sci-Fi","Director":"Ridley Scott","Writer":"Jon Spaihts, Damon Lindelof, Dan O'Bannon (based on elements created by), Ronald Shusett (based on elements created by)","Actors":"Noomi Rapace, Michael Fassbender, Charlize Theron, Idris Elba","Plot":"Following clues to the origin of mankind, a team finds a structure on a distant moon, but they soon realize they are not alone.","Language":"English, Scottish Gaelic","Country":"USA, UK","Awards":"Nominated for 1 Oscar. Another 6 wins & 46 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3NzIyNTA2NV5BMl5BanBnXkFtZTcwNzE2NjI4Nw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Rotten Tomatoes","Value":"72%"},{"Source":"Metacritic","Value":"65/100"}],"Metascore":"65","imdbRating":"7.0","imdbVotes":"504,770","imdbID":"tt1446714","Type":"movie","DVD":"09 Oct 2012","BoxOffice":"$126,464,904","Production":"20th Century Fox","Website":"http://www.prometheus-movie.com/","Response":"True"},
{"Title":"Robin Hood","Year":"2010","Rated":"PG-13","Released":"14 May 2010","Runtime":"140 min","Genre":"Action, Adventure, Drama","Director":"Ridley Scott","Writer":"Brian Helgeland (screenplay), Brian Helgeland (story), Ethan Reiff (story), Cyrus Voris (story)","Actors":"Russell Crowe, Cate Blanchett, Max von Sydow, William Hurt","Plot":"Birth of a legend. Following King Richard's death in France, archer Robin Longstride, along with Will Scarlett, Alan-a-Dale and Little John, returns to England. They encounter the dying Robert of Locksley, whose party was ambushed by treacherous Godfrey, who hopes to facilitate a French invasion of England. Robin promises the dying knight he will return his sword to his father Walter in Nottingham. Here Walter encourages him to impersonate the dead man to prevent his land being confiscated by the crown, and he finds himself with Marian, a ready-made wife. Hoping to stir baronial opposition to weak King John and allow an easy French take-over, Godfrey worms his way into the king's service as Earl Marshal of England and brutally invades towns under the pretext of collecting Royal taxes. Can Robin navigate the politics of barons, royals, traitors, and the French?","Language":"English, French, Ukrainian","Country":"USA, UK","Awards":"1 win & 14 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTM5NzcwMzEwOF5BMl5BanBnXkFtZTcwNjg5MTgwMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.7/10"},{"Source":"Rotten Tomatoes","Value":"43%"},{"Source":"Metacritic","Value":"53/100"}],"Metascore":"53","imdbRating":"6.7","imdbVotes":"224,937","imdbID":"tt0955308","Type":"movie","DVD":"21 Sep 2010","BoxOffice":"$105,219,735","Production":"Universal","Website":"http://www.robinhoodthemovie.com/","Response":"True"},
{"Title":"Body of Lies","Year":"2008","Rated":"R","Released":"10 Oct 2008","Runtime":"128 min","Genre":"Action, Drama, Romance","Director":"Ridley Scott","Writer":"William Monahan (screenplay), David Ignatius (novel)","Actors":"Leonardo DiCaprio, Russell Crowe, Mark Strong, Golshifteh Farahani","Plot":"Roger Ferris is a CIA operative in the Middle East; Ed Hoffman is his control at Langley. Cynicism is everywhere. In Amman, Roger works with Hani Salaam, Jordan's head of security, whose only dictum is \"Don't lie to me.\" The Americans are in pursuit of a cleric who leads a group placing bombs all over Europe. When Hani rebukes Ed's demand that Jordan allow the Americans to use one of Jordan's double agents, Roger and Ed hatch a plan to bring the cleric to them. The plan is complicated by its being a secret from Hani and by Roger's attraction to a local nurse. Satellites and cell phones, bodies and lies: modern warfare.","Language":"English, Arabic","Country":"USA, UK","Awards":"2 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTgzOTY3MTM0OV5BMl5BanBnXkFtZTcwNjc5MTI5MQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"},{"Source":"Rotten Tomatoes","Value":"55%"},{"Source":"Metacritic","Value":"57/100"}],"Metascore":"57","imdbRating":"7.1","imdbVotes":"185,472","imdbID":"tt0758774","Type":"movie","DVD":"17 Feb 2009","BoxOffice":"$39,380,442","Production":"Warner Bros. Pictures","Website":"http://www.body-of-lies.com/","Response":"True"},
{"Title":"American Gangster","Year":"2007","Rated":"R","Released":"02 Nov 2007","Runtime":"157 min","Genre":"Biography, Crime, Drama","Director":"Ridley Scott","Writer":"Steven Zaillian, Mark Jacobson (article)","Actors":"Denzel Washington, Russell Crowe, Chiwetel Ejiofor, Josh Brolin","Plot":"Following the death of his employer and mentor, Bumpy Johnson, Frank Lucas establishes himself as the number one importer of heroin in the Harlem district of Manhattan. He does so by buying heroin directly from the source in South East Asia and he comes up with a unique way of importing the drugs into the United States. As a result, his product is superior to what is currently available on the street and his prices are lower. His alliance with the New York Mafia ensures his position. It is also the story of a dedicated and honest policeman, Richie Roberts, who heads up a joint narcotics task force with the Federal government. Based on a true story.","Language":"English","Country":"USA, UK","Awards":"Nominated for 2 Oscars. Another 12 wins & 35 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTkyNzY5MDA5MV5BMl5BanBnXkFtZTcwMjg4MzI3MQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"80%"},{"Source":"Metacritic","Value":"76/100"}],"Metascore":"76","imdbRating":"7.8","imdbVotes":"342,665","imdbID":"tt0765429","Type":"movie","DVD":"19 Feb 2008","BoxOffice":"$130,127,620","Production":"Universal Pictures","Website":"http://www.americangangster.net","Response":"True"},
{"Title":"A Good Year","Year":"2006","Rated":"PG-13","Released":"10 Nov 2006","Runtime":"117 min","Genre":"Comedy, Drama, Romance","Director":"Ridley Scott","Writer":"Marc Klein (screenplay), Peter Mayle (novel)","Actors":"Freddie Highmore, Albert Finney, Russell Crowe, Rafe Spall","Plot":"After years of no contact with his Uncle Henry, London banker and bond trader Max Skinner learns that Henry has died intestate, so Max inherits a château and vineyard in Provence. Max spent part of his childhood there, learning maxims and how to win and lose, and honing his killer instinct (at chess, which serves him well in finance). Max goes to France intent on selling the property. He spends a few days there, getting the property ready to show. Memories, a beautiful woman, and a young American who says she's Henry's illegitimate daughter interrupt his plans. Did Max the boy know things that Max the man has forgotten?","Language":"English, French, Russian","Country":"USA, UK","Awards":"1 win & 2 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BODE4NDY3MjUxNV5BMl5BanBnXkFtZTYwMTMwODI3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.9/10"},{"Source":"Rotten Tomatoes","Value":"26%"},{"Source":"Metacritic","Value":"47/100"}],"Metascore":"47","imdbRating":"6.9","imdbVotes":"76,551","imdbID":"tt0401445","Type":"movie","DVD":"27 Feb 2007","BoxOffice":"$7,365,004","Production":"20th Century Fox","Website":"http://www.agoodyear.com/","Response":"True"},
{"Title":"Kingdom of Heaven","Year":"2005","Rated":"R","Released":"06 May 2005","Runtime":"144 min","Genre":"Action, Adventure, Drama","Director":"Ridley Scott","Writer":"William Monahan","Actors":"Martin Hancock, Michael Sheen, Nathalie Cox, Eriq Ebouaney","Plot":"It is the time of the Crusades during the Middle Ages - the world shaping 200-year collision between Europe and the East. A blacksmith named Balian has lost his family and nearly his faith. The religious wars raging in the far-off Holy Land seem remote to him, yet he is pulled into that immense drama. Amid the pageantry and intrigues of medieval Jerusalem he falls in love, grows into a leader, and ultimately uses all his courage and skill to defend the city against staggering odds. Destiny comes seeking Balian in the form of a great knight, Godfrey of Ibelin, a Crusader briefly home to France from fighting in the East. Revealing himself as Balian's father, Godfrey shows him the true meaning of knighthood and takes him on a journey across continents to the fabled Holy City. In Jerusalem at that moment--between the Second and Third Crusades--a fragile peace prevails, through the efforts of its enlightened Christian king, Baldwin IV, aided by his advisor Tiberias, and the military restraint of the legendary Muslim leader Saladin Ayubi . But Baldwin's days are numbered, and strains of fanaticism, greed, and jealousy among the Crusaders threaten to shatter the truce. King Baldwin's vision of peace--a kingdom of heaven--is shared by a handful of knights, including Godfrey of Ibelin, who swear to uphold it with their lives and honor. As Godfrey passes his sword to his son, he also passes on that sacred oath: to protect the helpless, safeguard the peace, and work toward harmony between religions and cultures, so that a kingdom of heaven can flourish on earth. Balian takes the sword and steps into history.","Language":"English, Arabic, Latin, Italian","Country":"USA, UK, Spain, Germany, Morocco","Awards":"5 wins & 14 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjE2MTIwNjg0MV5BMl5BanBnXkFtZTcwNjAxODIzMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.2/10"},{"Source":"Rotten Tomatoes","Value":"39%"},{"Source":"Metacritic","Value":"63/100"}],"Metascore":"63","imdbRating":"7.2","imdbVotes":"233,422","imdbID":"tt0320661","Type":"movie","DVD":"11 Oct 2005","BoxOffice":"$47,259,055","Production":"20th Century Fox","Website":"http://www.kingdomofheavenmovie.com/","Response":"True"},
{"Title":"Matchstick Men","Year":"2003","Rated":"PG-13","Released":"12 Sep 2003","Runtime":"116 min","Genre":"Comedy, Crime, Drama","Director":"Ridley Scott","Writer":"Eric Garcia (book), Nicholas Griffin (screenplay), Ted Griffin (screenplay)","Actors":"Nicolas Cage, Sam Rockwell, Alison Lohman, Bruce Altman","Plot":"Meet Roy and Frank, a couple of professional small-time con artists. What Roy, a veteran of the grift, and Frank, his ambitious protégé, are swindling these days are \"water filtration systems,\" bargain-basement water filters bought by unsuspecting people who pay ten times their value in order to win bogus prizes like cars, jewelry and overseas vacations--which they never collect. These scams net the flim-flam men a few hundred here, another thousand there, which eventually adds up to a lucrative partnership. Roy's private life, however, is not so successful. An obsessive-compulsive agoraphobe with no personal relationships to call his own, Roy is barely hanging on to his wits, and when his idiosyncrasies begin to threaten his criminal productivity he's forced to seek the help of a psychoanalyst just to keep him in working order. While Roy is looking for a quick fix, his therapy begets more than he bargained for: the revelation that he has a teenage daughter--a child whose existence he suspected but never dared confirm. What's more troubling, 14-year-old Angela wants to meet the father she never knew. At first, Angela's appearance disrupts her neurotic father's carefully ordered routine. Soon, however, with his own unique spin on parenthood, Roy begins to enjoy a relationship he never dreamed of having with his daughter. But while he develops paternal feelings for the 14-year-old, she's developing a fascination with Daddy's questionable career.","Language":"English","Country":"USA","Awards":"5 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NjMyNjIyMF5BMl5BanBnXkFtZTYwOTgzMDI3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"82%"},{"Source":"Metacritic","Value":"61/100"}],"Metascore":"61","imdbRating":"7.3","imdbVotes":"112,101","imdbID":"tt0325805","Type":"movie","DVD":"01 Jun 2004","BoxOffice":"$36,873,198","Production":"Warner Bros. Pictures","Website":"http://matchstickmenmovie.warnerbros.com/","Response":"True"},
{"Title":"Black Hawk Down","Year":"2001","Rated":"R","Released":"18 Jan 2002","Runtime":"144 min","Genre":"Drama, History, War","Director":"Ridley Scott","Writer":"Mark Bowden (book), Ken Nolan (screenplay)","Actors":"Josh Hartnett, Ewan McGregor, Tom Sizemore, Eric Bana","Plot":"Action/war drama based on the best-selling book detailing a near-disastrous mission in Somalia on October 3, 1993. On this date nearly 100 U.S. Army Rangers, commanded by Capt. Mike Steele, were dropped by helicopter deep into the capital city of Mogadishu to capture two top lieutenants of a Somali warlord. This led to a large and drawn-out firefight between the Army Ranges, US Special Forces, and hundreds of Somali gunmen; resulting in the destruction of two U.S. Black Hawk helicopters. The film focuses on the heroic efforts of various Rangers to get to the downed black hawks, centering on SSG Eversmann, leading the Ranger unit Chalk Four to the first black hawk crash site, Chief Warrant Officer Durant who was captured after being the only survivor of the second black hawk crash, as well as many others who were involved.","Language":"English, Somali, Arabic","Country":"USA, UK","Awards":"Won 2 Oscars. Another 8 wins & 37 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BYWMwMzQxZjQtODM1YS00YmFiLTk1YjQtNzNiYWY1MDE4NTdiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"76%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"7.7","imdbVotes":"314,211","imdbID":"tt0265086","Type":"movie","DVD":"11 Jun 2002","BoxOffice":"$108,585,355","Production":"Sony Pictures","Website":"http://www.spe.sony.com/movies/blackhawkdown","Response":"True"},
{"Title":"Hannibal","Year":"2001","Rated":"R","Released":"09 Feb 2001","Runtime":"131 min","Genre":"Crime, Drama, Thriller","Director":"Ridley Scott","Writer":"Thomas Harris (novel), David Mamet (screenplay), Steven Zaillian (screenplay)","Actors":"Anthony Hopkins, Julianne Moore, Gary Oldman, Ray Liotta","Plot":"The continuing saga of Hannibal Lecter, the murdering cannibal. He is presently in Italy and works as a curator at a museum. Clarice Starling, the FBI agent whom he aided to apprehend a serial killer, was placed in charge of an operation but when one of her men botches it, she's called to the mat by the Bureau. One high ranking official, Paul Krendler has it in for her. But she gets a reprieve because Mason Verger, one of Lecter's victims who is looking to get back at Lecter for what Lecter did to him, wants to use Starling to lure him out. When Lecter sends her a note she learns that he's in Italy so she asks the police to keep an eye out for him. But a corrupt policeman who wants to get the reward that Verger placed on him, tells Verger where he is. But they fail to get him. Later Verger decides to frame Starling which makes Lecter return to the States. And the race to get Lecter begins.","Language":"English, Italian, Japanese","Country":"USA, UK","Awards":"8 wins & 17 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZGMwN2I2OTctNzViYS00MjhjLTk5OWEtYmJiMDMxMmVjYTVhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.8/10"},{"Source":"Rotten Tomatoes","Value":"39%"},{"Source":"Metacritic","Value":"57/100"}],"Metascore":"57","imdbRating":"6.8","imdbVotes":"221,552","imdbID":"tt0212985","Type":"movie","DVD":"21 Aug 2001","BoxOffice":"$163,877,858","Production":"MGM","Website":"http://www.mgm.com/hannibal","Response":"True"},
{"Title":"Gladiator","Year":"2000","Rated":"R","Released":"05 May 2000","Runtime":"155 min","Genre":"Action, Adventure, Drama","Director":"Ridley Scott","Writer":"David Franzoni (story), David Franzoni (screenplay), John Logan (screenplay), William Nicholson (screenplay)","Actors":"Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed","Plot":"Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death, the Emperor chooses Maximus to be his heir over his own son, Commodus, and a power struggle leaves Maximus and his family condemned to death. The powerful general is unable to save his family, and his loss of will allows him to get captured and put into the Gladiator games until he dies. The only desire that fuels him now is the chance to rise to the top so that he will be able to look into the eyes of the man who will feel his revenge.","Language":"English","Country":"USA, UK","Awards":"Won 5 Oscars. Another 53 wins & 101 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"76%"},{"Source":"Metacritic","Value":"67/100"}],"Metascore":"67","imdbRating":"8.5","imdbVotes":"1,085,243","imdbID":"tt0172495","Type":"movie","DVD":"21 Nov 2000","BoxOffice":"N/A","Production":"Dreamworks Distribution LLC","Website":"http://www.gladiator-thefilm.com","Response":"True"},
{"Title":"Memento","Year":"2000","Rated":"R","Released":"25 May 2001","Runtime":"113 min","Genre":"Mystery, Thriller","Director":"Christopher Nolan","Writer":"Christopher Nolan (screenplay), Jonathan Nolan (short story \"Memento Mori\")","Actors":"Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior","Plot":"Memento chronicles two separate stories of Leonard, an ex-insurance investigator who can no longer build new memories, as he attempts to find the murderer of his wife, which is the last thing he remembers. One story line moves forward in time while the other tells the story backwards revealing more each time.","Language":"English","Country":"USA","Awards":"Nominated for 2 Oscars. Another 55 wins & 55 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"80/100"}],"Metascore":"80","imdbRating":"8.5","imdbVotes":"933,618","imdbID":"tt0209144","Type":"movie","DVD":"04 Sep 2001","BoxOffice":"$23,844,220","Production":"Newmarket Films","Website":"http://www.otnemem.com","Response":"True"},
{"Title":"Batman Begins","Year":"2005","Rated":"PG-13","Released":"15 Jun 2005","Runtime":"152 min","Genre":"Action, Adventure, Thriller","Director":"Christopher Nolan","Writer":"Bob Kane (characters), David S. Goyer (story), Christopher Nolan (screenplay), David S. Goyer (screenplay)","Actors":"Christian Bale, Michael Caine, Liam Neeson, Katie Holmes","Plot":"When his parents are killed, billionaire playboy Bruce Wayne relocates to Asia where he is mentored by Henri Ducard and Ra's Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as 'Batman'. But it doesn't stay quiet for long.","Language":"English, Urdu, Mandarin","Country":"USA, UK","Awards":"Nominated for 1 Oscar. Another 14 wins & 71 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"84%"},{"Source":"Metacritic","Value":"70/100"}],"Metascore":"70","imdbRating":"8.3","imdbVotes":"1,079,730","imdbID":"tt0372784","Type":"movie","DVD":"18 Oct 2005","BoxOffice":"$204,100,000","Production":"Warner Bros. Pictures","Website":"http://www.batmanbegins.com/","Response":"True"},
{"Title":"The Prestige","Year":"2006","Rated":"PG-13","Released":"20 Oct 2006","Runtime":"130 min","Genre":"Drama, Mystery, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Priest (novel)","Actors":"Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo","Plot":"In the end of the Nineteenth Century, in London, Robert Angier, his beloved wife Julia McCullough and Alfred Borden are friends and assistants of a magician. When Julia accidentally dies during a performance, Robert blames Alfred for her death and they become enemies. Both become famous and rival magicians, sabotaging the performance of the other on the stage. When Alfred performs a successful trick, Robert becomes obsessed trying to disclose the secret of his competitor with tragic consequences.","Language":"English","Country":"USA, UK","Awards":"Nominated for 2 Oscars. Another 5 wins & 36 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"76%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"8.5","imdbVotes":"945,501","imdbID":"tt0482571","Type":"movie","DVD":"20 Feb 2007","BoxOffice":"$53,100,000","Production":"Buena Vista Pictures","Website":"http://touchstone.movies.go.com/index.html?dlink=prestige","Response":"True"},
{"Title":"The Dark Knight","Year":"2008","Rated":"PG-13","Released":"18 Jul 2008","Runtime":"152 min","Genre":"Action, Crime, Drama","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine","Plot":"Set within a year after the events of Batman Begins, Batman, Lieutenant James Gordon, and new district attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City until a mysterious and sadistic criminal mastermind known only as the Joker appears in Gotham, creating a new wave of chaos. Batman's struggle against the Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent and Rachel Dawes.","Language":"English, Mandarin","Country":"USA, UK","Awards":"Won 2 Oscars. Another 151 wins & 154 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"9.0","imdbVotes":"1,848,050","imdbID":"tt0468569","Type":"movie","DVD":"09 Dec 2008","BoxOffice":"$533,316,061","Production":"Warner Bros. Pictures/Legendary","Website":"http://thedarkknight.warnerbros.com/","Response":"True"},
{"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible - inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 152 wins & 204 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"86%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.8","imdbVotes":"1,636,262","imdbID":"tt1375666","Type":"movie","DVD":"07 Dec 2010","BoxOffice":"$292,568,851","Production":"Warner Bros. Pictures","Website":"http://inceptionmovie.warnerbros.com/","Response":"True"},
{"Title":"The Dark Knight Rises","Year":"2012","Rated":"PG-13","Released":"20 Jul 2012","Runtime":"164 min","Genre":"Action, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt","Plot":"Despite his tarnished reputation after the events of The Dark Knight, in which he took the rap for Dent's crimes, Batman feels compelled to intervene to assist the city and its police force which is struggling to cope with Bane's plans to destroy the city.","Language":"English, Arabic","Country":"UK, USA","Awards":"Nominated for 1 BAFTA Film Award. Another 38 wins & 101 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"8.4","imdbVotes":"1,257,286","imdbID":"tt1345836","Type":"movie","DVD":"03 Dec 2012","BoxOffice":"$448,130,642","Production":"Warner Bros. Pictures","Website":"http://www.thedarkknightrises.com/","Response":"True"},
{"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"07 Nov 2014","Runtime":"169 min","Genre":"Adventure, Drama, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow","Plot":"Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.","Language":"English","Country":"USA, UK, Canada, Iceland","Awards":"Won 1 Oscar. Another 43 wins & 143 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"71%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.6","imdbVotes":"1,102,530","imdbID":"tt0816692","Type":"movie","DVD":"31 Mar 2015","BoxOffice":"$158,737,441","Production":"Paramount Pictures","Website":"http://www.InterstellarMovie.com/","Response":"True"},
{"Title":"Dunkirk","Year":"2017","Rated":"PG-13","Released":"21 Jul 2017","Runtime":"106 min","Genre":"Action, Drama, History","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Fionn Whitehead, Damien Bonnard, Aneurin Barnard, Lee Armstrong","Plot":"Evacuation of Allied soldiers from Belgium, the British Empire, and France, who were cut off and surrounded by the German army from the beaches and harbor of Dunkirk, France, between May 26- June 04, 1940, during Battle of France in World War II.","Language":"English, French, German","Country":"UK, Netherlands, France, USA","Awards":"1 win & 4 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BN2YyZjQ0NTEtNzU5MS00NGZkLTg0MTEtYzJmMWY3MWRhZjM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"94/100"}],"Metascore":"94","imdbRating":"8.3","imdbVotes":"228,161","imdbID":"tt5013056","Type":"movie","DVD":"N/A","BoxOffice":"$186,881,004","Production":"Warner Bros. Pictures","Website":"http://www.dunkirkmovie.com","Response":"True"},
{"Title":"Hard Eight","Year":"1996","Rated":"R","Released":"28 Feb 1997","Runtime":"101 min","Genre":"Crime, Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson","Actors":"Philip Baker Hall, John C. Reilly, Gwyneth Paltrow, Samuel L. Jackson","Plot":"John has lost all his money. He sits outside a diner in the desert when Sydney happens along, buys him coffee, then takes him to Reno and shows him how to get a free room without losing much money. Under Sydney's fatherly tutelage, John becomes a successful small-time professional gambler, and all is well, until he falls for Clementine, a cocktail waitress and sometimes hooker.","Language":"English","Country":"USA","Awards":"2 wins & 8 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BY2E0Mjc3MWEtNjYxNC00Y2UwLThmNTQtYmUyMTIzMzE2MTMwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"83%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"7.3","imdbVotes":"31,375","imdbID":"tt0119256","Type":"movie","DVD":"05 Oct 1999","BoxOffice":"N/A","Production":"MGM","Website":"N/A","Response":"True"},
{"Title":"Boogie Nights","Year":"1997","Rated":"R","Released":"31 Oct 1997","Runtime":"155 min","Genre":"Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson","Actors":"Luis Guzmán, Burt Reynolds, Julianne Moore, Rico Bueno","Plot":"Adult film director Jack Horner is always on the lookout for new talent and it's only by chance that he meets Eddie Adams who is working as a busboy in a restaurant. Eddie is young, good looking and plenty of libido to spare. Using the screen name Dirk Diggler, he quickly rises to the top of his industry winning awards year after year. Drugs and ego however come between Dirk and those around him and he soon finds that fame is fleeting.","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 29 wins & 49 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjMzNzkwNjEyOF5BMl5BanBnXkFtZTgwOTY3Njc3NjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"85/100"}],"Metascore":"85","imdbRating":"7.9","imdbVotes":"202,001","imdbID":"tt0118749","Type":"movie","DVD":"07 Apr 1998","BoxOffice":"N/A","Production":"New Line Cinema","Website":"N/A","Response":"True"},
{"Title":"Magnolia","Year":"1999","Rated":"R","Released":"07 Jan 2000","Runtime":"188 min","Genre":"Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson","Actors":"Pat Healy, Genevieve Zweig, Mark Flanagan, Neil Flynn","Plot":"24 hours in L.A.; it's raining cats and dogs. Two parallel and intercut stories dramatize men about to die: both are estranged from a grown child, both want to make contact, and neither child wants anything to do with dad. Earl Partridge's son is a charismatic misogynist; Jimmy Gator's daughter is a cokehead and waif. A mild and caring nurse intercedes for Earl, reaching the son; a prayerful and upright beat cop meets the daughter, is attracted to her, and leads her toward a new calm. Meanwhile, guilt consumes Earl's young wife, while two whiz kids, one grown and a loser and the other young and pressured, face their situations. The weather, too, is quirky.","Language":"English, German, French","Country":"USA","Awards":"Nominated for 3 Oscars. Another 28 wins & 51 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZjk3YThkNDktNjZjMS00MTBiLTllNTAtYzkzMTU0N2QwYjJjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"84%"},{"Source":"Metacritic","Value":"77/100"}],"Metascore":"77","imdbRating":"8.0","imdbVotes":"254,327","imdbID":"tt0175880","Type":"movie","DVD":"25 Jul 2000","BoxOffice":"N/A","Production":"New Line Cinema","Website":"http://www.magnoliamovie.com","Response":"True"},
{"Title":"Punch-Drunk Love","Year":"2002","Rated":"R","Released":"01 Nov 2002","Runtime":"95 min","Genre":"Comedy, Drama, Romance","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson","Actors":"Adam Sandler, Jason Andrews, Don McManus, Emily Watson","Plot":"Barry Egan hates himself and hates his life. The only male among eight siblings, Barry is treated poorly by his overbearing sisters. Despite owning his own business, he has gotten nowhere in life largely because of his insecurities. He leads a solitary life, which allows him to hide his violent outbursts that occur when he's frustrated. His solitude however allows him to think, he stumbling upon a scheme to travel the world on a pittance, travel which he has never done. Concurrently, he meets two people who pull him in two different directions. The first is Lena Leonard, a friend of his sister Elizabeth. Barry is slow to realize that Lena is attracted to him, he making her make all the first moves. Lena is eventually able to get Barry out of his shell, she who sticks around despite his obvious problems. His burgeoning relationship and thus new life with Lena is threatened by the second, \"Georgia\", who he contacted in an effort to alleviate his loneliness. Georgia and her \"band of brothers\" do whatever they can get get out of Barry what they want, no matter the price to Barry.","Language":"English","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 14 wins & 35 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BYmE1OTY4NjgtYjcwNC00NWE4LWJiNGMtZmVhYTdlMWE1YzIxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"79%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"7.3","imdbVotes":"118,703","imdbID":"tt0272338","Type":"movie","DVD":"24 Jun 2003","BoxOffice":"$17,800,000","Production":"Columbia Pictures","Website":"http://www.punchdrunklove.com/","Response":"True"},
{"Title":"There Will Be Blood","Year":"2007","Rated":"R","Released":"25 Jan 2008","Runtime":"158 min","Genre":"Drama, History","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson (screenplay), Upton Sinclair (novel)","Actors":"Daniel Day-Lewis, Martin Stringer, Matthew Braden Stringer, Jacob Stringer","Plot":"The intersecting life stories of Daniel Plainview and Eli Sunday in early twentieth century California presents miner-turned-oilman Daniel Plainview, a driven man who will do whatever it takes to achieve his goals. He works hard but also takes advantage of those around him at their expense if need be. His business partner/son (H.W.) is, in reality, an \"acquired\" child whose true biological single-parent father (working on one of Daniel's rigs) died in a workplace accident. Daniel is deeply protective of H.W. if only for what H.W. brings to the partnership. Eli Sunday is one in a pair of twins whose family farm Daniel purchases for the major oil deposit located on it. Eli, a local preacher and a self-proclaimed faith healer, wants the money from the sale of the property to finance his own church. The lives of the two competitive men often clash as Daniel pumps oil off the property and tries to acquire all the surrounding land at bargain prices to be able to build a pipeline to the coast, and as Eli tries to build his own religious empire.","Language":"English, American Sign Language","Country":"USA","Awards":"Won 2 Oscars. Another 106 wins & 136 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"91%"},{"Source":"Metacritic","Value":"93/100"}],"Metascore":"93","imdbRating":"8.1","imdbVotes":"413,509","imdbID":"tt0469494","Type":"movie","DVD":"08 Apr 2008","BoxOffice":"$40,133,435","Production":"Paramount Vantage","Website":"http://www.therewillbeblood.com","Response":"True"},
{"Title":"The Master","Year":"2012","Rated":"R","Released":"21 Sep 2012","Runtime":"144 min","Genre":"Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson","Actors":"Joaquin Phoenix, Price Carson, Mike Howard, Sarah Shoshana David","Plot":"Returning from Navy service in World War II, Freddie Quell drifts through a series of breakdowns. Finally he stumbles upon a cult which engages in exercises to clear emotions and he becomes deeply involved with them.","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 76 wins & 179 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NjQ5MzMwMF5BMl5BanBnXkFtZTcwMjczNTAzOA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"},{"Source":"Rotten Tomatoes","Value":"85%"},{"Source":"Metacritic","Value":"86/100"}],"Metascore":"86","imdbRating":"7.1","imdbVotes":"116,364","imdbID":"tt1560747","Type":"movie","DVD":"26 Feb 2013","BoxOffice":"$15,800,000","Production":"The Weinstein Company","Website":"http://www.themasterfilm.com/","Response":"True"},
{"Title":"Inherent Vice","Year":"2014","Rated":"R","Released":"09 Jan 2015","Runtime":"148 min","Genre":"Comedy, Crime, Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson (written for the screen by), Thomas Pynchon (based on the novel by)","Actors":"Joanna Newsom, Katherine Waterston, Joaquin Phoenix, Jordan Christian Hearn","Plot":"During the psychedelic 60s and 70s Larry \"Doc\" Sportello is surprised by his former girlfriend and her plot for her billionaire boyfriend, his wife, and her boyfriend. A plan for kidnapping gets shaken up by the oddball characters entangled in this groovy kidnapping romp based upon the novel by Thomas Pynchon.","Language":"English, Japanese","Country":"USA","Awards":"Nominated for 2 Oscars. Another 16 wins & 94 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjI2ODQ2NzUwMl5BMl5BanBnXkFtZTgwNjU3NTE4MjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.7/10"},{"Source":"Rotten Tomatoes","Value":"73%"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"6.7","imdbVotes":"71,973","imdbID":"tt1791528","Type":"movie","DVD":"28 Apr 2015","BoxOffice":"$6,100,613","Production":"Warner Bros. Pictures","Website":"http://inherentvicemovie.com/","Response":"True"}
]

/* 
Gruppeopgaver
Opgave 1
Opbygning af webside til præsentation af film */

var e0 = document.getElementById("0");
e0.innerHTML = filmliste[0].Title+' ('+filmliste[0].Year+')';
e0.id = filmliste[0].imdbID;


var e1 = document.getElementById("1");
e1.innerHTML = '<p>'+filmliste[1].Title+' ('+filmliste[1].Year+')'+'</p>';
e1.id = filmliste[1].imdbID;


var e2 = document.getElementById("2");
e2.innerHTML = '<p>'+filmliste[2].Title+' ('+filmliste[2].Year+')'+'</p>';
e2.id = filmliste[2].imdbID;


var e3 = document.getElementById("3");
e3.innerHTML = '<p>'+filmliste[3].Title+' ('+filmliste[3].Year+')'+'</p>';
e3.id = filmliste[3].imdbID;

/*
Opgave 2 
Farvelæg filmtitler ud fra bedømmelser  */

function Farve(){
for (i = 0; i < 3; i++){

	if (filmliste[i].imdbRating < 7) {
		document.getElementById(filmliste[i].imdbID).setAttribute("class", "tekstred");
	}
	else if (filmliste[i].imdbRating >= 7 && filmliste[i].imdbRating  < 8){
		document.getElementById(filmliste[i].imdbID).setAttribute("class", "tekstblue");
	}
	else if (filmliste[i].imdbRating >= 8){
		document.getElementById(filmliste[i].imdbID).setAttribute("class", "tekstgreen");
	}
}
}

/* Opgave 1 
Gør det muligt at få vist mere information om filmen, ved at trykke på knappen under titlen 
4 knapper med hver sin tilhørende funktion */

var info0 = 0;
 function VisMere0() {
        if(info0 == 0){
            document.getElementById("t0").innerHTML = "<p>"+"Filmen er "+filmliste[0].Runtime+" lang og er instrueret af "+filmliste[0].Director+"</p>";
            info0 = 1;
        }
        else if (info0 == 1){
        document.getElementById("t0").innerHTML = "";
        info0 = 0;
    }
}

var info1 = 0;
 function VisMere1() {
        if(info1 == 0){
            document.getElementById("t1").innerHTML = "<p>"+"Filmen er "+filmliste[1].Runtime+" lang og er instrueret af "+filmliste[1].Director+"</p>";
            info1 = 1;
        }
        else if (info1 == 1){
        document.getElementById("t1").innerHTML = "";
        info1 = 0;
    }
}

var info2 = 0;
 function VisMere2() {
        if(info2 == 0){
            document.getElementById("t2").innerHTML = "<p>"+"Filmen er "+filmliste[2].Runtime+" lang og er instrueret af "+filmliste[2].Director+"</p>";
            info2 = 1;
        }
        else if (info2 == 1){
        document.getElementById("t2").innerHTML = "";
        info2 = 0;
    }
}

var info3 = 0;
 function VisMere3() {
        if(info3 == 0){
            document.getElementById("t3").innerHTML = "<p>"+"Filmen er "+filmliste[3].Runtime+" lang og er instrueret af "+filmliste[3].Director+"</p>";
            info3 = 1;
        }
        else if (info3 == 1){
        document.getElementById("t3").innerHTML = "";
        info3 = 0;
    }
}


/* Opgave 3/4
Procentuel sammenligning af to lister 
SamL(filmliste[18].Actors, filmliste[19].Actors) giver 25% fordi der er 1 ud af 4 overlap af skuespillere*/



var overLapTæl0 = 0;
function OverLap0(a, b) {
	var a = a.split(",");
	var b = b.split(",");
	for (i = 0; i < 4; i++){
		if (a[i] == b[i]){
		overLapTæl0 += 1
		overLapTæl0 = (overLapTæl0/4)*100
	} else if (overLapTæl0 = 0) {
		document.getElementById(filmliste[1].imdbID).setAttribute("class", "tekstred");
	} 
}
}


